### ISSUE TITLE
is coriolis free ,how can i try it?

### ISSUE THREAD

**Issue by willzhang** [cloudbase/coriolis-web#556]
i can't find any docs about how to install coriolis, anyone can help?
i want try it to migrate vmware vm to openstack.

**Comment by aznashwan** [comment]
Hello Will, and thanks for taking interest in Coriolis!

Because Coriolis is a fully distributed system which integrates with OpenStack technologies, it is non-trivial to deploy it manually.
There are numerous supporting services (such as a database, AMQP server, Keystone for authentication and multitenancy, and so on) which are required for a fully functional Coriolis installation.

For ease of deployment and user convenience, we offer pre-built Coriolis appliance images with everything set up in advance.

Please contact info@cloudbasesolutions.com or our [contact form on our website](https://cloudbase.it/about/#contact) if you are interested in taking Coriolis for a spin.
